#server:
#  port: 9984
#  servlet:
#    context-path: /api
#spring:
#  datasource:
#    url: jdbc:mysql://115.175.74.221:3306/api?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#
